# Generated by Django 3.2.8 on 2021-11-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
    ]
